<?php use Helper\Html; ?>
<?= Html::css('/css/login/style.css') ?>
<div class="container main">
    <div class="logo">
        <a href="http://www.aayongche.com/">
            <img src="/img/logo.png" alt="AA用车" width="180">
        </a>
        <b class="regist"></b>
    </div>
    <form method="post" action="/login/register/userRegister" onsubmit="return checkLogin();">
        <input type="hidden" id="uuid" name="uuid" value="1234">

        <div class="container">
            <div class="nav-label user-reg active">
                <span><a href="/login/register">个人用户</a></span>
            </div>
            <div class="nav-label company-reg">
                <span><a href="/login/register/company">企业用户</a></span>
            </div>
            <div class="login_center">
                <div class="center-bg clearfix">
                    <div class="span8">
                        <div id="register_form" class="form-horizontal">
                            <div class="control-group ">
                                <label class="control-label" for="mobile">手机号</label>

                                <div class="controls">
                                    <input class="text" id="mobile" name="mobile" maxlength="11" type="text"
                                           onblur="javascript:checkMobile()"><b>*</b>
                                    <span class="help-inline" style="display: none;">请输入手机号</span>
                                </div>
                            </div>
                            <div class="control-group ">
                                <label class="control-label" for="code">验证码</label>

                                <div class="controls">
                                    <input maxlength="6" class="input-small" id="code" name="code" type="text"
                                           onblur="javascript:checkCode();">&nbsp;
                                    <button type="button" id="genCode" class="btn btn-info">&nbsp;获取验证码&nbsp;</button>
                                    <b>*</b>
                                    <span class="help-inline" style="display: none;">请输入验证码</span>
                                </div>
                            </div>
                            <div class="control-group ">
                                <label class="control-label" for="password">密码</label>

                                <div class="controls">
                                    <input class="text" id="password" name="password" type="password"
                                           maxlength="25" onblur="javascript:checkPassword();"><b>*</b>
                                    <span class="help-inline" style="display: none;">请输入密码</span>
                                </div>
                            </div>
                            <div class="control-group ">
                                <label class="control-label" for="repassword">确认密码</label>

                                <div class="controls">
                                    <input class="text" id="repassword" name="repassword" type="password"
                                           maxlength="20" onblur="javascript:checkRePassword();"><b>*</b>
                                    <span class="help-inline" style="display: none;">请输入确认密码</span>
                                </div>
                            </div>
                            <div class="control-group ">
                                <label class="control-label" for="name">用户姓名</label>

                                <div class="controls">
                                    <input class="text" id="name" name="name" type="text" maxlength="8"
                                           onblur="javascript:checkName();"><b>*</b>
                                    <span class="help-inline" style="display: none;">请输入用户姓名</span>
                                </div>
                            </div>
                            <div class="control-group ">
                                <label class="control-label" for="sex">性别</label>

                                <div class="controls">
                                    <label class="radio inline">
                                        <input type="radio" name="sex" id="male" value="0" checked> <i
                                            class="icon-male"></i> 先生
                                    </label>
                                    <label class="radio inline">
                                        <input type="radio" name="sex" id="female" value="1"> <i
                                            class="icon-female"></i> 女士
                                    </label>
                                </div>
                            </div>

                            <div class="control-group">
                                <div class="controls">
                                    <label class="checkbox">
                                        <input type="checkbox" checked>我已阅读并同意
                                        <a href="#">《AA用车用户注册协议》</a>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="span1"></div>
                        <div class="control-group span4">
                            <div class="controls">
                                <button class="btn btn-large btn-block btn-danger" type="submit">注 册
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="span4">
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
<script language="javascript">

    //手机号后台验证标志
    var checkMobileTarget = false;
    //验证码后台验证标志
    var checkCodeTarget = false;

    //验证手机号
    function checkMobile() {
        var mobile = $('#mobile').val();
        if (mobile == '') {
            $('#mobile').parent().parent().addClass('error');
            $('#mobile').parent().children('span').html('请输入手机号!');
            $('#mobile').parent().children('span').show();
            return false
        } else if (!validateRules.isMobile(mobile)) {
            $('#mobile').parent().parent().addClass('error');
            $('#mobile').parent().children('span').html('请输入正确手机号!');
            $('#mobile').parent().children('span').show();
            return false;
        } else {
            $.getJSON("/login/register/validate?mobile=" + escape(mobile) + "&r=" + Math.random(), function (data) {
                if (data.success == 1) {
                    $('#mobile').parent().parent().addClass('error');
                    $('#mobile').parent().children('span').html('该手机号已经注册!');
                    $('#mobile').parent().children('span').show();
                } else {
                    $('#mobile').parent().parent().removeClass('error');
                    $('#mobile').parent().children('span').html('<i class="icon-ok" style="color:green;"></i>');
                    $('#mobile').parent().children('span').show();
                    checkMobileTarget = true;
                }
            })
        }
        return true;
    }

    function checkCode() {
        var code = $('#code').val();
        if (code == '') {
            $('#code').parent().parent().addClass('error');
            $('#code').parent().children('span').html('请输入验证码!');
            $('#code').parent().children('span').show();
            return false
        } else {
            $.getJSON("/login/register/validate?code=" + escape(code) + "&r=" + Math.random(), function (data) {
                if (data.success == 0) {
                    $('#code').parent().parent().addClass('error');
                    $('#code').parent().children('span').html('验证码输入错误!');
                    $('#code').parent().children('span').show();
                } else {
                    $('#code').parent().parent().removeClass('error');
                    $('#code').parent().children('span').html('<i class="icon-ok" style="color:green;"></i>');
                    $('#code').parent().children('span').show();
                    checkCodeTarget = true;
                }
            })
        }
        return true;
    }

    function checkPassword() {
        var passwrod = $('#password').val();
        if (passwrod == '') {
            $('#password').parent().parent().addClass('error');
            $('#password').parent().children('span').html('请输入密码!');
            $('#password').parent().children('span').show();
            return false
        } else if (!validateRules.isPwd(passwrod)) {
            $('#password').parent().parent().addClass('error');
            $('#password').parent().children('span').html('密码只能由英文、数字及标点符号组成!');
            $('#password').parent().children('span').show();
            return false;
        } else if (!validateRules.betweenLength(passwrod, 6, 20)) {
            $('#password').parent().parent().addClass('error');
            $('#password').parent().children('span').html('密码长度只能在6-20位字符之间!');
            $('#password').parent().children('span').show();
            return false;
        } else {
            $('#password').parent().parent().removeClass('error');
            $('#password').parent().children('span').html('<i class="icon-ok" style="color:green;"></i>');
            $('#password').parent().children('span').show();
            checkRePassword();
        }
        return true;
    }

    function checkRePassword() {
        var passwrod = $('#password').val();
        var repasswrod = $('#repassword').val();
        if (repasswrod == '') {
            $('#repassword').parent().parent().addClass('error');
            $('#repassword').parent().children('span').html('请输入确认密码!');
            $('#repassword').parent().children('span').show();
            return false
        } else if (!validateRules.isPwdRepeat(passwrod, repasswrod)) {
            $('#repassword').parent().parent().addClass('error');
            $('#repassword').parent().children('span').html('两次输入密码不一致!');
            $('#repassword').parent().children('span').show();
            return false;
        } else {
            $('#repassword').parent().parent().removeClass('error');
            $('#repassword').parent().children('span').html('<i class="icon-ok" style="color:green;"></i>');
            $('#repassword').parent().children('span').show();
        }
        return true;
    }

    function checkName() {
        var name = $('#name').val();
        if (name == '') {
            $('#name').parent().parent().addClass('error');
            $('#name').parent().children('span').html('请输入用户姓名!');
            $('#name').parent().children('span').show();
            return false
        } else {
            $('#name').parent().parent().removeClass('error');
            $('#name').parent().children('span').html('<i class="icon-ok" style="color:green;"></i>');
            $('#name').parent().children('span').show();
        }
        return true;
    }

    function checkLogin() {
        if (checkMobile() && checkCode() && checkPassword() && checkRePassword() && checkName() && checkMobileTarget && checkCodeTarget) {
            return true;
        }
        return false;
    }

    //验证码按钮
    $('#genCode').click(function () {
        $.getJSON("/login/register/genCheckcode?r=" + Math.random(), function (data) {
            //if (data == 'ok') {
            alert(data);
            $('#genCode').attr('disabled', 'true');
            //}
        })
    })
</script>
