<?php use Helper\Html; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>AA用车 用户登录</title>
    <?= Html::importJquery(); ?>
    <?= Html::importBootstrap(); ?>
    <?= Html::css('/css/login/style.css') ?>
</head>
<body>
<?= $_content_ ?>
<footer>
    <div class="container">
        <div class="text-center">
            <div class="copyright">Copyright@2013&nbsp;&nbsp;AA用车 aayongche.com&nbsp;版权所有</div>
        </div>
    </div>
</footer>
</body>
</html>
