<?php use Helper\Html; ?>
<?= Html::css('/css/order/style.css') ?>
<div class="alert">
    <div class="form-inline">
        <fieldset>
            <legend>订单查询</legend>
            <label>预定时间:</label>
            <input type="text" placeholder="开始时间"> 至 <input type="text" placeholder="结束时间">
            <button type="submit" class="btn btn-warning">查 询</button>
        </fieldset>
    </div>
</div>
<ul class="nav nav-tabs">
    <li class="active">
        <a href="#">最新订单(1)</a>
    </li>
    <li><a href="#">已结束订单(0)</a></li>
</ul>
<div>
    <table class="table table-bordered table-hover">
        <thead>
        <tr>
            <th>订单号</th>
            <th>乘车人</th>
            <th>预定时间</th>
            <th>上车时间</th>
            <th>服务类型</th>
            <th>订单状态</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>100001</td>
            <td>张三</td>
            <td>2013-6-17 14:18</td>
            <td>2013-6-18 10:00</td>
            <td>送机服务</td>
            <td>等待分配车辆</td>
            <td><a href="#">取消订单</a></td>
        </tr>
        </tbody>
    </table>
    <div class="pagination pagination-right">
        <ul>
            <li><a href="#">上一页</a></li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">下一页</a></li>
        </ul>
    </div>
</div>
