<?php use Helper\Html; ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>AA用车</title>
    <?= Html::importJquery(); ?>
    <?= Html::importBootstrap(); ?>
    <?= Html::importFontawesome(); ?>
    <?= Html::css('/css/layout/main.css') ?>
</head>
<body>
<div id="top_bar" class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="./index.html">AA用车</a>

            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li>
                        <a href="./index.html">首页</a>
                    </li>
                </ul>
                <ul class="nav pull-right">
                    <li><a href="/order/list">我的订单</a></li>
                    <li class="divider-vertical"></li>
                    <li><a href="/finance/transaction">我的账户</a></li>
                    <li class="divider-vertical"></li>
                    <li><a href="#">帮助中心</a></li>
                    <li class="divider-vertical"></li>
                    <li><a href="#"><i class="icon-phone-sign icon-large"></i> 400-010-6767</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="logo">
        <a href="http://www.aayongche.com/">
            <img src="/img/logo.png" alt="AA用车" width="180">
        </a>
    </div>
</div>

<div class="container">
    <hr>
    <div class="row">
        <div id="menu" class="span3">
            <div class="dropdown">
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                    <li class="main"><a tabindex="-1" href="#">个人账户</a></li>
                    <li class="divider"></li>
                    <li><a tabindex="-1" href="/order/list">我的订单</a></li>
                    <li><a tabindex="-1" href="/finance/transaction">账户余额</a></li>
                    <li><a tabindex="-1" href="/other/opensoon">信用卡管理</a></li>
                    <li><a tabindex="-1" href="/other/opensoon">我的优惠卷</a></li>
                    <li class="divider"></li>
                    <li class="main"><a tabindex="-1" href="#">个人信息</a></li>
                    <li class="divider"></li>
                    <li><a tabindex="-1" href="/other/opensoon">个人资料</a></li>
                    <li><a tabindex="-1" href="/other/opensoon">常用地址</a></li>
                    <li><a tabindex="-1" href="/other/opensoon">常用乘车人</a></li>
                    <li><a tabindex="-1" href="/other/opensoon">发票信息</a></li>
                    <li><a tabindex="-1" href="/other/opensoon">修改密码</a></li>
                </ul>
            </div>
        </div>
        <div class="span9">
            <?php echo $_content_; ?>
        </div>
    </div>
</div>
<footer>
    <div class="container">
        <div class="text-center">
            <div class="copyright">Copyright©2013&nbsp;&nbsp;AA用车 aayongche.com&nbsp;版权所有</div>
        </div>
    </div>
</footer>
</body>
</html>
